name: 'Sailfish SDK Build'
author: "Richard Liebscher <r1tschy@posteo.de>"
description: 'Build your RPM for Sailfish'

inputs:
  arch:
    description: 'Architecture to compile for (armv7hl or i486)'
    required: false
    default: 'armv7hl'
  release:
    description: 'Version of Sailfish to compile for (for example 3.3.0.14)'
    required: false
    default: 'latest'
  check:
    description: 'Perform quality checks. (See `mb2 check` for more information)'
    required: false
    default: 'false'
  source-dir:
    description: ''
    required: false
    default: ''
  image:
    description: 'Basename of Docker image to use (name without tag)'
    required: false
    default: 'r1tschy/sailfishos-platform-sdk'
  enable-debug:
    description: 'Enable debug build (passes --enabled-debug to mb2)'
    required: false
    default: ""
  output-dir:
    description: 'Directory the resulting RPM artifacts are placed in'
    required: false
    default: './RPMS'
  specfile:
    description: 'Path to *.spec file'
    required: false
    default: ""
  fix-version:
    description: 'Overwrite version from git information (`true` or `false` are allowed) (see `mb2 --fix-version` for more information)'
    required: false
    default: ""

outputs:
  rpm-dir: 
    description: "Folder with RPM artifacts"
    value: ${{ steps.script.outputs.rpm-dir }}

runs:
  using: "composite"
  steps: 
    - id: script
      run: python3 ${{ github.action_path }}/script.py
      shell: bash
      env:
        INPUT_ARCH: ${{ inputs.arch }}
        INPUT_RELEASE: ${{ inputs.release }}
        INPUT_CHECK: ${{ inputs.check }}
        INPUT_SOURCE_DIR: ${{ inputs.source-dir }}
        INPUT_IMAGE: ${{ inputs.image }}
        INPUT_ENABLE_DEBUG: ${{ inputs.enable-debug }}
        INPUT_OUTPUT_DIR: ${{ inputs.output-dir }}
        INPUT_SPECDIR: ${{ inputs.specfile }}
        INPUT_FIX_VERSION: ${{ inputs.fix-version }}
